import "./globals.css";
import type { Metadata } from "next";

import dynamic from 'next/dynamic';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const Pug = dynamic(
    () => import('@/components/pug'),
    { ssr: false }
  );

  
  return (
    <html lang="en">
      <body 
        className="
        items-center flex justify-center min-h-screen p-0 m-0 overflow-hidden
      *:box-border *:bg-[#947cb0] box-border bg-[#947cb0]
      "
      >
        <div>
           <Pug />
        </div>
      </body>
    </html>
  );
}
